services:
  - type: web
    name: db-connect-checker-api
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 8080
      - key: FRONTEND_URL
        value: "https://data-baseconnect-checker.vercel.app"
